# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 862eef4290d9f7feb0c6f36fe03a859652bdea0cf3ca13cb8f3f3cca64ed274d4aebba3f704e6a78e7792b143371e0e699797551c3e14a70f13a4f3bf1b12c5e

test:
  secret_key_base: c206fd6e316111d2514272bd22f832d9acca746b44050b251731e619a092569871573378c02fb97708b472bb1e7907a9a23635646ca650e7b9a9808dc1622b63

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
